### ISSUE TITLE
REVIT crash since latest windows security update

### ISSUE THREAD

**Issue by sentabrina** [pyrevitlabs/pyRevit#2103]
**🙏 Please use the search in the issue section before filing a new issue**

---

# 🐞 Describe the bug

REVIT 2020 refuses to open since Monday 19/02/2024

the problem comes from latest windows security update which blocks pyRevit. Once desinstalled - all works.

Please help. 

I can’t provide any more help since my company has already uninstalled pyRevit. 
the version I have had installed was downloaded on 6 December 2022. It worked great until the crash.

Twenty94470 works maybe somewhere south of Paris and maybe in the same company. His comment is correct 👍

Wish this is repaired. Hard to continue working without pyRevit.

# ⏲️ Expected behavior

# 🖼 Screenshots of the issue

# 🖥️ Hardware and Software Setup (please complete the following information):
 - pyRevit Version [e.g. 22]
 - pyRevit Environment: Open a command prompt 🖥 and run the command below. Replace these lines with the results. Take a look at this markdown guide and wrap the command results in ``` when pasting here for correct formatting.

👉 `pyrevit env`

# Additional context

**Comment by sanzoghenzo** [comment]
Hi @sentabrina , please fill out the information requested, so that we can better help you.

You mention the "latest windows security update", can you be more specific? Which version is it? Windows 10 or 11?

**Comment by sentabrina** [comment]
I can not be more specific about the security update version right now.
It is windows 10.
may you help me to find the info I will be willing to help you resolve the issue

**Comment by sentabrina** [comment]
It is my 1st time ever to report a bug on GitHub. Sorry for my noobiness :D

**Comment by sanzoghenzo** [comment]
All the text that follows your request in the first post is not there just to scare you 😉
Read it, follow the instructions and fill the variuos sections with the information needed.
That way we should have most of the data to understand the problem.

Also, you mention that revit "crashes" and "refuses to open", but are there any error messages? What does they say?
If there are no messages whatsoever, pleas attach the last revit journal as it could be very useful to diagnose the problem.

**Comment by Twenty94470** [comment]
Since the windows update KB5034763 on Windows 10, every computer in our company had an error message when they launch revit with pyrevit. 

Autodesk recommend to uninstall your product to fix the situation : https://www.autodesk.fr/support/technical/article/caas/sfdcarticles/sfdcarticles/FRA/PyRevitLoader-Error-Loading-pyRevit-message-when-opening-Revit.html

**Comment by sanzoghenzo** [comment]
@Twenty94470 and @sentabrina, assuming you're part of the same company, I insist you complete the information in the first post as instructed.
 
Also, [follow these instructions](https://github.com/eirannejad/pyRevit/issues/2055#issuecomment-1900674214) to see if it gets fixed.

**Comment by Twenty94470** [comment]
Yeah, two Github users with the same problem == same company, sorry but you are a bad profiler. keep coding, you seem to be better on it. ( I hope ...)

I'll let you know if your tips fix the situation.

and @sentabrina see you tomorrow at the office :DDDDDDD

**Comment by sanzoghenzo** [comment]
@Twenty94470 please keep a friendly tone. If I've offended you, I'm sorry. I'm a bit sad for your sarcasm, I'm offering my free time to help you and get bad jokes in return.

My assumption was: since @sentabrina didn't give us all the info needed to diagnose the problem, and neither did you, the only way for you to know that you two are talking about the same issue is that you know each other and have already talked about this outside this channel.
If this is not the case, your statement "users with the same problem", while it could be true, is completely unverified.

**Comment by Twenty94470** [comment]
Hello sorry for the tone and bad joke its was not appropriate i was just surprise by your answer. 

We clearly identify the problem with the february update from Microsoft so when he says in introduction "the problem comes from latest windows security update". I've prefered to add a comment (with more détails) and not create a duplicate issue. But yes maybe its not the same problem. 

I hope the windows update will have limited impact and as i say i'll let you know if your solution is working.

Thanks for your free time to develop this useful tools.regards

**Comment by jmcouffin** [comment]
Please refer to the Bug Report description and fill in all the details required so that we can pin down or reproduce the error. Without that, the issue will get closed with no resolution
I have 2 systems, Win10 and win11pro. No problems whatsoever between Win/Revit/pyRevit.
