### ISSUE TITLE
Chocolatey package install gets 404 Error

### ISSUE THREAD

**Issue by DailenG** [pyrevitlabs/pyRevit#2110]
---

# 🐞 Describe the bug

choco install pyrevit gets a 404 error, checking the chocolatey source shows the URL is different than the GitHub Release URL

Github Release URL: https://github.com/eirannejad/pyRevit/releases/download/v4.8.14.24016%2B1909/pyRevit_CLI_4.8.14.24016_admin_signed.exe
Chocolatey Package URL: https://github.com/eirannejad/pyRevit/releases/download/v4.8.14.24016/pyRevit_CLI_4.8.14.24016_admin_signed.exe

**Comment by sanzoghenzo** [comment]
Hi @DailenG, thanks for bringing this to our attention.

I've tracked down the problem to this lines:

https://github.com/eirannejad/pyRevit/blob/6f72bb9b3b5389d281a2ad1eba2995e94be32d9b/dev/_release.py#L283-L287

Since the rest of the pipeline uses the pyrevit build version and not the installer version, `install` argument should be `False`.

@eirannejad can you please fix the `release\choco\tools\chocolateyinstall.ps1` to add the `+1909` and push it manually?

Also, after some git blaming, I think that the chocolatey package is broken since version 4.8.10 or 4.8.11!

**Comment by jmcouffin** [comment]
@sanzoghenzo merged!
Nice!

Do you still need Ehsan to edit the PS1 script, or can we close this issue?

**Comment by jmcouffin** [comment]
https://github.com/eirannejad/pyRevit/blob/6d7db7ab3b08a3d9790454ea87334da07afd3d16/release/choco/tools/chocolateyinstall.ps1#L5

Like this, @sanzoghenzo ?
`$url64      = 'https://github.com/eirannejad/pyRevit/releases/download/v4.8.14.24016+1909/pyRevit_CLI_4.8.14.24016_admin_signed.exe'`

Which branch?

**Comment by sanzoghenzo** [comment]
It has to be done manually on a machine with the chocolatey token available, because the ci pipeline is already set to publish the next version. So I suppose only Ehsan can do it

**Comment by eirannejad** [comment]
- [ ] Replace current choco package with one that has correct url

**Comment by jmcouffin** [comment]
@sanzoghenzo 
I now have the choco logins, if you want we can have a zoom session to get this fixed

**Comment by jmcouffin** [comment]
> Do we need to fix the old packages?

you are right, we don't, I wen tthru the thread to quickly.
thks
I will close that one
