### ISSUE TITLE
Connect PyRevit To Design Automation Revit

### ISSUE THREAD

**Issue by chuongmep** [pyrevitlabs/pyRevit#2288]
## Is your feature request related to a problem? Please describe

Some challange I want to try, don't know whether have any people doing that yet ? 
https://stackoverflow.com/questions/77806477/pyrevit-should-be-supported-in-design-automation-for-revit
 

## Describe the solution you'd like

No solution availbale  for now

## Describe alternatives you've considered

Some of part like engine will run in cloud and execute script. 

## Additional context

Just see some people ask about that, but it will be good because I also want try something relate to execute process use python script.

**Comment by sanzoghenzo** [comment]
My suggestion? learn c# and build a plugin with that :wink: 

The main advantage of using python and pyrevit is the ability to do RAD (Rapid Application/Add-in Prototyping), so that you can change the code of a command without reloading revit. That advantage is completely lost on Design Automation API.

There would be a huge work to extract the python engine part just to run a script;
It's much more easy to create a new plugin with just the IronPython Engine and the instructions to run your script.
But at this point, you'll be better off just writing the script directly in c#, to avoid the IronPython external dependency altogether and stay in the realm of managed, more secure code.

**Comment by sanzoghenzo** [comment]
Closing this because it is out of scope and there are no resources to tackle this
