### ISSUE TITLE
[Bug]: Tooltip images not displaying

### ISSUE THREAD

**Issue by mawdesign** [pyrevitlabs/pyRevit#2291]
### ✈ Pre-Flight checks

- [X] I **don't have SentinelOne** antivirus installed (see above for the solution)
- [X] I have **searched in the issues** (open and closed) but couldn't find a similar issue
- [X] I have **searched in the [pyRevit Forum](https://discourse.pyrevitlabs.io)** for similar issues
- [X] I already **followed the [installation troubleshooting guide](https://pyrevitlabs.notion.site/Installation-issues-f6495adb56254e9e8021f8a68e3b2ab7) thoroughly**
- [X] I am using the **latest pyRevit Version**

### 🐞 Describe the bug

"tooltip.png" in bundle folders is not displaying on hover, this appears to be the same problem as in #1265, but for images rather than video. Below is my solution, which was to copy the code from `set_tooltip_video()` to `set_tooltip()`, and revise to use Windows Image Control and the `load_bitmapimage()` function.

### ⌨ Error/Debug Message

```shell
Fails silently, just no image displayed.
```

### ♻️ To Reproduce

1. Go to pyRevit tab, Templates, hover over Generate FilledRegion Swatches
2. after a brief pause the tooltip should expand and show the image

### ⏲️ Expected behavior

Expected:
![image](https://github.com/pyrevitlabs/pyRevit/assets/46857735/f4fb9514-9107-407c-af52-6cf201f4e40d)

Only get this, (it never expands):
![image](https://github.com/pyrevitlabs/pyRevit/assets/46857735/effb25f1-8702-48b7-b95d-df97c21c9b90)

### 🖥️ Hardware and Software Setup (please complete the following information)

```shell
Windows 11 Pro
Tried in Revit 2020 and 2022
Output from pyrevit env:
 
Microsoft Windows 10 [Version 10.0.22621]
Admin Access: No
%APPDATA%: "C:\Users\<username>\AppData\Roaming"
Latest Installed .Net Framework: 4.8
No .Net Target Packs are installed.
Installed .Net-Core Target Packs: v7.0.402
pyRevit CLI v4.8.13.23182+2215
```

### Additional context

This solved the problem for me...
coreutils > ribbon.py
```
    def set_tooltip_image(self, tooltip_image):
        try:
            adwindows_obj = self.get_adwindows_object()
            if isinstance(self.get_rvtapi_object().ToolTip, str):
                exToolTip = self.get_rvtapi_object().ToolTip
            else:
                exToolTip = None
            if adwindows_obj:
                adwindows_obj.ToolTip = AdWindows.RibbonToolTip()
                adwindows_obj.ToolTip.Title = self.ui_title
                adwindows_obj.ToolTip.Content = exToolTip
                _StackPanel = System.Windows.Controls.StackPanel()
                _image = System.Windows.Controls.Image()
                _image.Source = load_bitmapimage(tooltip_image)
                _StackPanel.Children.Add(_image)
                adwindows_obj.ToolTip.ExpandedContent = _StackPanel
                adwindows_obj.ResolveToolTip()
            else:
                self.tooltip_image = tooltip_image
        except Exception as ttimage_err:
            raise PyRevitUIError('Error setting tooltip image {} | {} '
                                 .format(tooltip_image, ttimage_err))
```
I am still figuring out how to do PRs for git repositories which have branches.

**Comment by sanzoghenzo** [comment]
Hi, Thanks for looking into this!
You can select the branch `develop-4` while creating the PR, so that it will be added to pyrevit versions 4; we will then take the changes to the upcoming pyrevit version 5.

One thing, though: I would change the code to avoid repetitions like this:

```python
ex_tooltip = self.get_rvtapi_object().ToolTip
if not isinstance(ex_tooltip, str): 
    ex_tooltip = None
```
This code sould be also moves inside the `if adwindows_obj` block, as it is only used there.
I would also invernali the if statement block, so that the else part, wich is the shoetest, will come first

```python
if not adwindows_obj:
    self.tooltip_image = tooltip_image
else:
    # rest of the code
```

I know the code is copied from existing one, but it wasn't properly vetted... I would like to ensure a bit of code style/quality for new code from now on 😉

**Comment by mawdesign** [comment]
Thanks, I've made the changes to both images and video tooltips to avoid repetitions, however, I'm not convinced that the back-up plan should go first simply because it is shortest, I would prefer to avoid `if not` to maintain readability.

The ability to select a branch while creating a PR is something I have not gotten working yet - the problem seems to be with creating a fork based on the branch, rather than main - I'll do some more Googling and YouTube watching on the weekend to see if I can figure it out.

**Comment by sanzoghenzo** [comment]
> I'm not convinced that the back-up plan should go first simply because it is shortest, I would prefer to avoid `if not` to maintain readability

Maybe in this case  it can be left as is, but in many other case the if branch is so long (and that's anorher code smell, but I'm digressing) that the one-line else branch gets lost some pages down. The `if not` is perfectly fine for readability, is the cognitive load to keep track of what the else is referring to that is more important.

One could also use a return in the `if not` branch and get rid if the else statement to reduce indentations and gain another bit of readability 

```python
if not adwindows_obj:
    self.tooltip_image = tooltip_image
    return
# rest of the code
```

But we don’t have any code style agreed upon (yet), so this is only my personal opinion after 9 years of daily python coding 😉 



> the problem seems to be with creating a fork based on the branch, rather than main

Yes sorry, you should do your changes in your local develop-4 branch in order to just have your edits pulled to the pyrevitlabs repository. To sum up:

- fork the pyrevit repository
- clone you fork locally
- switch to the develop-4 branch
- make your edits
- push your develop-4 branch co your clone
- create a pr.

If your fork only contains the master branch, you need to first get the develop-4 branch from pyrevitlabs (tha _upstream_ repo)

```
git remote add usptream git@github.com:pyrevitlabs/pyRevit.git
git fetch upstream
git checkout -b develop-4 upstream/develop-4
```

If you already committed the changes in the main branch, you can cherry-pick the commit to copy it to the cirrent branch.

If you use visual studio code with the git graph plugin, you can do these things graphically (I admit I had to lookup the right syntax of the commands because I mostri use that or pyCharm integrated git features)

**Comment by mawdesign** [comment]
Thanks, I think I've figured it out by forking and then editing directly through the browser (following steps you listed). I already had a fork, just needed to add the branch.
