### ISSUE TITLE
Revit 2025 installer

### ISSUE THREAD

**Issue by Testesting2024** [pyrevitlabs/pyRevit#2415]
Does this addin work for Revit 2025? I'm getting the following error after installing it:

![Screenshot 2024-10-12 085456](https://github.com/user-attachments/assets/a5e92361-485c-4604-a8a0-c49b9ed1f87b)

**Comment by sanzoghenzo** [comment]
Hi @Testesting2024, a couple of observation:

- please use the "bug report" template instead of the "new feature" one and fill all the needed info.
- use the search to find if someone else has/had your issue, you'll find out that Revit 2025 is still not supported by Revit 4.x versions, you need to use the WIP installer you can find in the [homepage](https://www.pyrevitlabs.io/).
